Add manifest.yaml for MongoDB
hasura/cli-plugins-index pull request #291
Opened 2024-03-22 01:43 UTC by dmoverton

2024-03-22 06:14 UTC, SandeepSamba commented on plugins/ndc-mongodb/v0.0.1/manifest.yaml
> +name: mongodb
The file path (which says `ndc-mongodb`) and the name here (which says `mongodb`) must be the same

2024-03-22 06:15 UTC, SandeepSamba commented on plugins/ndc-mongodb/v0.0.1/manifest.yaml
> +name: mongodb
Recommend to follow whatever convention `ndc-postgres` team is going with

2024-03-22 06:15 UTC, SandeepSamba commented on plugins/ndc-mongodb/v0.0.1/manifest.yaml
> +        to: "hasura-mongodb"
Same, follow same naming conventions uniformly across binary names for all platforms

2024-03-22 06:17 UTC, SandeepSamba requested changes
Please follow a unform naming convention. It does not matter if it is `ndc-mongodb` or `mongodb`, but pls ensure it is uniform everywhere

2024-03-25 02:56 UTC, dmoverton commented on plugins/ndc-mongodb/v0.0.1/manifest.yaml
> +name: mongodb
Done

2024-03-25 02:57 UTC, dmoverton commented on plugins/ndc-mongodb/v0.0.1/manifest.yaml
> +        to: "hasura-mongodb"
Done

2024-03-25 21:31 UTC, merged